### ISSUE TITLE
AssertionError: Found no NVIDIA driver on your system. Please check that you

### ISSUE THREAD

**Issue by doramir** [bastings/annotated_encoder_decoder#1]
when running this code on a computer without cuda 
```python
        train_perplexity = run_epoch((rebatch(PAD_INDEX, b) for b in train_iter), 
                                     model,
                                     SimpleLossCompute(model.generator, criterion, optim),
                                     print_every=print_every)
```
any way to fix it?

**Comment by bastings** [comment]
Maybe it is related to torch text: https://github.com/pytorch/text/issues/236
Could you check if it is solved with the latest version?

**Comment by VictorMwachi** [comment]
i am trying to run my openNmt server.py brings this error yet i installed pytorch with cuda 10 from pytorch website
