### ISSUE TITLE
General discussion

### ISSUE THREAD

**Issue by AyeshaNirma** [bastings/annotated_encoder_decoder#2]
HI Bastings,

Thanks for your tutorial and documentation. Really appreciated. However, I was wondering have you ever tried this on time-series data (numerical)? In theory it should also work on temporal data with some tweaks as well. What are your thoughts in general and if you have some snippet etc.

Thanks
anyways

**Comment by bastings** [comment]
Hi Ayesha,

Machine Translation is also temporal if you see a sentence as a sequence of words over time.
I haven't used this on numerical time series though. You might want to check out this example for that: https://github.com/pytorch/examples/tree/master/time_sequence_prediction
