### ISSUE TITLE
beam search implementation for this repository

### ISSUE THREAD

**Issue by zmf0507** [bastings/annotated_encoder_decoder#3]
Hello @bastings 
Thanks a lot for such a detailed notebook. I was wondering if we can have beam search implementation along with greedy search for this repo. If you have any such implementation, can you push it or redirect me to any other repo which has implemented beam search for this repo?
Thanks. It will help much.

**Comment by bastings** [comment]
Hi! We've implemented beam search with Joey NMT which used this as a starting point. See https://github.com/joeynmt/joeynmt
